/*
=========================================
Aula 03 - WHERE
Banco: AdventureWorks2017
Data: 29/07/2026
Causa e efeito: Coleta de dados específcos único no sistema.
=========================================
*/

/*
OPERADOR    -    DESCRIÇÃO
=                IGUAL
>                MAIOR QUE
<                MENOR QUE
>=               MAIOR QUE OU IGUAL
<=               MENOR QUE OU IGUAL
<>               DIFERENTE DE
AND              OPERADOR LÓGICO + 
OR               OPERADOR LÓGICO OU

*/


-- Selecionar colunas específicas
SELECT *
FROM Production.Product
WHERE color <> "red"


/* #EXERCÍCIO 03#

  */