/*
=========================================
Less 10 - MIN - MAX - SUM - AVG
Database: AdventureWorks2017
Date: 16/08/2026
Cause and effect: These functions are used for incrementing and are self-explanatory.
=========================================
*/

-- MIN,MAX,SUM and AVG :

SELECT TOP MIN (LINETOTAL)                       --> 
FROM Sales.SalesOrderDetail                      --   

SELECT TOP MAX (LINETOTAL)                       --> 
FROM Sales.SalesOrderDetail

SELECT TOP SUM (LINETOTAL)                       --> 
FROM Sales.SalesOrderDetail

SELECT TOP AVG (LINETOTAL)                       --> 
FROM Sales.SalesOrderDetail
        
                                 

-- #EXERCÍCIOS 10#



